name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev cmake
    - name: Build executable
      run: |
        mkdir build
        cmake --build ./build --config Debug --target chip8_vm

  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev cmake
    - name: Build tests
      run: |
        mkdir build
        cmake --build ./build --config Debug --target run_tests
    - name: Run tests
      run: ./build/run_tests

  fuzz:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libsfml-dev cmake
    - name: Build fuzzer
      run: |
        mkdir build
        CXX=clang++ cmake --build ./build --config Debug --target fuzz
    - name: Run fuzzer
      run: ./build/fuzz corpus/ -max_len=4096 -dict=fuzzing_dictionary.txt -timeout=10 -runs=10000000‬
